Catch22/Controllers/CMSController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Catch22.Models;

namespace Catch22.Controllers
{
    [Authorize]
    public class CMSController : Controller
    {
        Catch22DataEntities db = new Catch22DataEntities();
        // GET: CMS
        public ActionResult Index()
        {
            CMSHomeViewModel model = new CMSHomeViewModel();
            model.NewsItems = db.News.Where(a => a.ExpirationDate > DateTime.Now).ToList();
            return View(model);
        }

        public ActionResult Calendar()
        {
            return View();
        }

        public ActionResult MemberBioEdit(int? id)
        {
            MemberBio memberBio;
            List<SelectListItem> allUsers = new List<SelectListItem>();
            if (id == null)
            {
                memberBio = db.MemberBios.Where(a => a.User.UserName == User.Identity.Name).Single();
            }
            else
            {
                if (!User.IsInRole("EditMemberBios"))
                {
                    memberBio = db.MemberBios.Where(a => a.User.UserName == User.Identity.Name).Single();
                }
                else
                {
                    memberBio = db.MemberBios.Where(a => a.UserID == id).Single();
                }
            }
            if (memberBio == null)
            {
                return HttpNotFound();
            }
            foreach (var user in db.Users)
            {
                var name = user.FirstName + " " + user.LastName;
                var item = new SelectListItem() { Text = name, Value = user.Id.ToString() };
                allUsers.Add(item);
            }
            ViewBag.AllUsers = allUsers;
            return View(memberBio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MemberBioEdit(MemberBio model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MemberBioEdit");
            }
            return View(model);
        }
    }
}

Catch22/Views/Shared/_CMSLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Catch 22 Admin</title>
    @Styles.Render("~/bundles/cssCMS")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">Catch 22 Admin</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav side-nav">
                        <li><a href="@Url.Action("Index", "CMS")"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                        @if (User.IsInRole("EditNews")) {
                            <li><a href="@Url.Action("Index", "News")"><i class="fa fa-edit"></i> Edit News</a></li> }
                        @if (User.IsInRole("EditSiteContent")) { 
                            <li><a href="@Url.Action("Index", "SiteContent")"><i class="fa fa-edit"></i> Edit Site Content</a></li> }
                        @if (User.IsInRole("EditPerformances")) { 
                            <li><a href="@Url.Action("Index", "Performance")"><i class="fa fa-edit"></i> Performances</a></li> }
                        @if (User.IsInRole("EditRepertoire")) { 
                            <li><a href="@Url.Action("Index", "Repertoire")"><i class="fa fa-edit"></i> Edit Repertoire</a></li> }
                        <li><a href="@Url.Action("Calendar", "CMS")"><i class="fa fa-calendar"></i> Calendar</a></li>
                    </ul>
                }

                <ul class="nav navbar-nav navbar-right navbar-user">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a href="@Url.Action("GroupContact", "CMS")"><i class="fa fa-group"></i> Group Contact Information</a></li>
                    }
                    <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Go to Catch22nc.org</a></li>
                    <li class="dropdown user-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-user"></i>
                            @if (User.Identity.IsAuthenticated)
                            {
                                @User.Identity.Name
                            }
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li><a href="@Url.Action("Manage", "Account")"><i class="fa fa-user"></i> Manage Account</a></li>
                                <li><a href="@Url.Action("MemberBioEdit", "CMS")"><i class="fa fa-edit"></i> Update Biography</a></li>
                                <li class="divider"></li>
                                <li><a href="@Url.Action("LogOff", "Account")"><i class="fa fa-power-off"></i> Log Out</a></li>
                            }
                            else
                            {
                                <li><a href="@Url.Action("Login", "Account")"><i class="fa fa-power-off"></i> Login</a></li>
                            }
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/admin-custom")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
    var deleteLinkObj

    $(".delete-link").click(function () {
        deleteLinkObj = $(this);
        $("#delete-dialog").dialog("open");
        return false;
    })

    $("#delete-dialog").dialog({
        autoOpen: false, width: 400, resizable: false, modal: true,
        buttons: {
            "Continue": function () {
                $.post(deleteLinkObj[0].href, function (data) {
                    if (data == "@Boolean.TrueString") {
                        deleteLinkObj.closest("tr").hide("fast");
                    }
                    else {
                    }
                });
                $(this).dialog("close");
            },
            "Cancel": function () {
                $(this).dialog("close");
            }
        }
    });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#changeMember").click(function () {
                var id = $("#selectUser").val();
                var url = "/CMS/MemberBioEdit/" + id;
                window.location.href = url;
            });
        });

    </script>
</body>
</html>

Catch22/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:image" content="~/Content/img/bg.jpg" />
    <title>@ViewBag.Title - Catch 22 - Fun A Cappella</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand" href="#top"><img class="nav-logo" src="img/logonew.png" alt="Catch 22" /></a> -->
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#top">Home</a></li>
                    <li><a href="#about">About Catch 22</a></li>
                    <li><a href="#performances">Performances</a></li>
                    <li><a href="#members">Members</a></li>
                    <li><a href="#repertoire">Our Music</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <!-- /Side Menu -->

    <!-- Full Page Image Header Area -->
    <div id="top" class="header">
        <div class="vert-text">
            <img class="logo" src="~/Content/img/new-logo.png" alt="Catch 22" />
            <h3>
                <a href="#about" class="btn btn-default btn-lg">Learn More!</a>
            </h3>
        </div>
    </div>

    <!-- /Full Page Image Header Area -->
    @RenderBody()
    <!-- Footer -->

    <footer>
        <div id="contact" class="container">
            <div class="row">
                <div class="text-center">
                    <h3>Interested in booking Catch 22 to perform at your event?</h3>
                    <h4>Send an email to booking@catch22nc.org today with the date and details for your event.  We would love to sing for you!</h4>
                </div>
            </div>
            <div class="row">
                <div class="container text-center">
                    <button class="btn btn-primary" id="flip" type="button">Click here to send us a message!</button>
                    <div id="panel">
                        <div id="success" class="">
                        </div>
                        <form role="form" action="" id="contactEmail" method="post">
                            <div class="form-group">
                                <label for="fromName">Name</label>
                                <input type="text" class="form-control" name="fromName">
                            </div>
                            <div class="form-group">
                                <label for="fromEmail">Email Address</label>
                                <input type="text" class="form-control" name="fromEmail">
                            </div>
                            <div class="form-group">
                                <label for="subject">Subject</label>
                                <input type="text" class="form-control" name="subject">
                            </div>
                            <div class="form-group">
                                <label for="emailText">Email Text</label>
                                <textarea class="form-control" name="emailText" rows="5"></textarea>
                            </div>
                            <button type="submit" name="submitEmail" id="submitEmail" class="btn btn-default">Send Message</button>
                        </form>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <h3>Check us out using the social media links below!</h3>
                    <ul class="list-inline">
                        <li><a href="https://www.facebook.com/catch22nc" target="blank"><i class="fa fa-facebook fa-4x"></i></a></li>
                        <li><a href="https://twitter.com/Catch22NC" target="blank"><i class="fa fa-twitter fa-4x"></i></a></li>
                        <li><a href="http://www.youtube.com/user/Catch22sings" target="blank"><i class="fa fa-youtube-square fa-4x"></i></a></li>
                    </ul>
                    <div class="top-scroll">
                        <a href="#top"><i class="fa fa-circle-arrow-up scroll fa-4x"></i></a>
                    </div>
                    <hr>
                    <p>Copyright &copy; Catch 22 2013</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- /Footer -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/mainsite")
    @RenderSection("scripts", required: false)
</body>
</html>