Catch22/Models/SiteContent.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catch22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteContent
    {
        public int SiteContentID { get; set; }
        public string ContentTitle { get; set; }
        public string ContentText { get; set; }
    }
}

Catch22/Controllers/SiteContentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catch22.Models;

namespace Catch22.Controllers
{
    [Authorize(Roles = "EditSiteContent")]
    public class SiteContentController : Controller
    {
        Catch22DataEntities db = new Catch22DataEntities();
        // GET: SiteContent
        public ActionResult Index(bool successMessage = false)
        {
            ViewBag.Success = successMessage;
            var model = db.SiteContents.Where(a => a.SiteContentID == 1).Single();
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(SiteContent model)
        {
            if (model == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { successMessage = true });
            }
            return View(model);
        }
    }
}

Catch22/Views/SiteContent/Index.cshtml
@model Catch22.Models.SiteContent

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CMSLayout.cshtml";
}
<div class="row">
    <div class="col-lg-6">
        <h1>Change Site Content</h1>
        @if (ViewBag.Success == true)
        {
            <div class='alert alert-success'>
                <p>
                    Updated Successfully
                </p>
            </div>
        }
        
        @using (Html.BeginForm("Update", "SiteContent", FormMethod.Post, new { @class="form form-horizontal"}))
        {
            @Html.HiddenFor(model => model.SiteContentID)
            @Html.HiddenFor(model => model.ContentTitle)
            <div class="form-group">
                @Html.LabelFor(model => model.ContentText, new { @class="control-label"})
                @Html.TextAreaFor(model => model.ContentText, new { rows = "7", @class="form-control"})
            </div>

            <button type="submit" class="btn btn-default">Update Blurb</button>
        }
    </div>
</div>