Catch22/Models/Repertoire.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catch22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repertoire
    {
        public int RepertoireID { get; set; }
        public string SongTitle { get; set; }
        public string OriginalArtist { get; set; }
        public string Soloist { get; set; }
        public System.DateTime DateEntered { get; set; }
        public bool Retired { get; set; }
    }
}

Catch22/Controllers/RepertoireController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catch22.Models;

namespace Catch22.Controllers
{
    [Authorize(Roles = "EditRepertoire")]
    public class RepertoireController : Controller
    {
        Catch22DataEntities db = new Catch22DataEntities();
        // GET: Repertoire
        public ActionResult Index()
        {
            RepertoireViewModel model = new RepertoireViewModel();
            model.AllRep = db.Repertoires.ToList();
            model.NewRep = new Repertoire();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(Repertoire model)
        {
            if (ModelState.IsValid)
            {
                db.Repertoires.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var repertoire = db.Repertoires.Where(a => a.RepertoireID == id).First();
            if (repertoire == null)
            {
                return HttpNotFound();
            }

            return View(repertoire);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Repertoire model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var repertoire = db.Repertoires.Where(a => a.RepertoireID == id).First();
            if (repertoire == null)
            {
                return HttpNotFound();
            }

            db.Repertoires.Remove(repertoire);
            db.SaveChanges();
            return Content(Boolean.TrueString);
        }
    }
}

Catch22/Views/Repertoire/Index.cshtml
@model Catch22.Models.RepertoireViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CMSLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1>Edit Current Repertoire</h1>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered">
                    <tr>
                        <th>Song Title</th>
                        <th>Original Artist</th>
                        <th>Soloist</th>
                        <th>Date Entered</th>
                        <th>Date Retired</th>
                        <th></th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.AllRep)
                    {
                        <tr>
                            <td>@item.SongTitle</td>
                            <td>@item.OriginalArtist</td>
                            <td>@item.Soloist</td>
                            <td>@item.DateEntered</td>
                            <td>@item.Retired</td>
                            <td><a href="@Url.Action("Edit", "Repertoire", new { id = @item.RepertoireID })">Edit</a></td>
                            <td>@Html.ActionLink("Delete", "Delete", new { id = item.RepertoireID }, new { @class = "delete-link" })</td>
                        </tr>
                    }         
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h2>Add a Song</h2>
        @Html.Partial("_NewRepertoire", Model.NewRep)
    </div>
    <div class="col-md-6">
        <h3>Notes</h3>
        <ul>
            <li>Refrain from deleting songs unless you made a mistake while entering or it is a song that is permanently removed.</li>
            <li>The "Retired" checkbox will cause a song to not show on the website.</li>
            <li>
                I'll be adding another field for "Seasonal" or "Special" songs like Christmas tunes and they will be in a different or extra
                section of the website
            </li>
        </ul>
    </div>
</div>

<div id="delete-dialog" title="Confirmation">
    <p>Are you sure you want to delete this item?</p>
</div>

Catch22/Views/Repertoire/_NewRepertoire.cshtml
@model Catch22.Models.Repertoire

@using (Html.BeginForm("Create", "Repertoire", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(model => model.SongTitle)
        @Html.TextBoxFor(model => model.SongTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.SongTitle)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OriginalArtist)
        @Html.TextBoxFor(model => model.OriginalArtist, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.OriginalArtist)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Soloist)
        @Html.TextBoxFor(model => model.Soloist, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Soloist)
    </div>
    <input type="submit" value="Create" class="btn btn-default" />
}