Catch22/Models/Performance.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catch22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Performance
    {
        public int PerformanceID { get; set; }
        public string PerformanceName { get; set; }

        [DisplayFormat(DataFormatString="{0:MM/dd/yyyy}", ApplyFormatInEditMode=true)]
        public System.DateTime PerformanceDate { get; set; }
        public string PerformanceTime { get; set; }
        public string Location { get; set; }
        public string Details { get; set; }
    }
}

Catch22/Controllers/PerformanceController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catch22.Models;

namespace Catch22.Controllers
{
    [Authorize(Roles = "EditPerformances")]
    public class PerformanceController : Controller
    {
        Catch22DataEntities db = new Catch22DataEntities();
        // GET: Performance
        public ActionResult Index()
        {
            PerformancesViewModel model = new PerformancesViewModel();
            model.AllPerformances = db.Performances.ToList();
            model.NewPerformance = new Performance();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(Performance model)
        {
            if (ModelState.IsValid)
            {
                db.Performances.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var performance = db.Performances.Where(a => a.PerformanceID == id).First();
            if (performance == null)
            {
                return HttpNotFound();
            }

            return View(performance);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Performance model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var performance = db.Performances.Where(a => a.PerformanceID == id).First();
            if (performance == null)
            {
                return HttpNotFound();
            }

            db.Performances.Remove(performance);
            db.SaveChanges();
            return Content(Boolean.TrueString);
        }
    }
}

Catch22/Views/Performance/Edit.cshtml
@model Catch22.Models.Performance

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_CMSLayout.cshtml";
}

<div class="row">
    <div class="col-md-6">
        <h2>Edit Performance</h2>
        @using (Html.BeginForm("Edit", "Performance", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.PerformanceID)

            <div class="form-group">
                @Html.LabelFor(model => model.PerformanceName, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.PerformanceName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PerformanceName)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PerformanceDate, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.PerformanceDate, new { @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.PerformanceDate)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PerformanceTime, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.PerformanceTime, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PerformanceTime)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Location)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Details, new { @class = "form-control", rows="3" })
                @Html.ValidationMessageFor(model => model.Details)
            </div>
            <input type="submit" value="Save" class="btn btn-default" />
        }
        <a href="@Url.Action("Index", "Performance")">Back to all Performances</a>
    </div>
</div>

Catch22/Views/Performance/Index.cshtml
@model Catch22.Models.PerformancesViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CMSLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1>Performances <small>All Performances</small></h1>
        <table class="table table-bordered">
            <tr>
                <td>Name</td>
                <td>Date</td>
                <td>Time</td>
                <td>Location</td>
                <td>Details</td>
                <td></td>
                <td></td>
            </tr>
            @foreach (var item in Model.AllPerformances)
            {
                <tr>
                    <td>@item.PerformanceName</td>
                    <td>@item.PerformanceDate</td>
                    <td>@item.PerformanceTime</td>
                    <td>@item.Location</td>
                    <td>@item.Details</td>
                    <td><a href="@Url.Action("Edit", "Performance", new { id = @item.PerformanceID })">Edit</a></td>
                    <td>@Html.ActionLink("Delete", "Delete", new { id = item.PerformanceID }, new { @class = "delete-link" })</td>
                </tr>
            }
        </table>
    </div>
</div><!-- /.row -->
<div class="row">
    <div class="col-md-6">
        <h2>Add a new event</h2>
        @Html.Partial("_NewPerformance", Model.NewPerformance)
    </div>
    <div class="col-md-6">
        <h3>Notes</h3>
        <ul>
            <li>If there are no gigs that are upcoming, the site will display a generic message and prompt to contact us for booking.</li>
            <li>Gigs that are past the current date will not show on the site.  I can change the timeframe or may add an override for this eventually.</li>
            <li>I think it is okay to delete this after a certain point but it may be good to keep a few in there if the event has just passed.</li>
        </ul>
    </div>
</div>

<div id="delete-dialog" title="Confirmation">
    <p>Are you sure you want to delete this item?</p>
</div>

Catch22/Views/Performance/_NewPerformance.cshtml
@model Catch22.Models.Performance

@using (Html.BeginForm("Create", "Performance", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Performance</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.PerformanceName)
            @Html.TextBoxFor(model => model.PerformanceName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PerformanceName)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PerformanceDate)
            @Html.TextBoxFor(model => model.PerformanceDate, new { @class = "form-control datepicker" })
            @Html.ValidationMessageFor(model => model.PerformanceDate)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PerformanceTime)
            @Html.TextBoxFor(model => model.PerformanceTime, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PerformanceTime)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location)
            @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Location)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details)
            @Html.TextAreaFor(model => model.Details, new { @class = "form-control", rows="3" })
            @Html.ValidationMessageFor(model => model.Details)
        </div>
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
}